import type { Metadata } from "next";
import {Space_Grotesk ,Inter} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const space_Grotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Resort Website Demo",
  description: "Generated by Resort Website Demo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${space_Grotesk.className} ${inter.variable} px-10 py-4 antialiased`}
      >
        <NavBar />
        <div className="">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
